language: ruby
rvm:
  - 2.3.3
  - 2.4.1
  - ruby-head
  - rbx-2

before_install:
  - gem install bundler

before_script: rake compile

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2


addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9

